### ISSUE TITLE
Connect to PAN from Smartphone

### ISSUE THREAD

**Issue by kingkian** [mk-fg/fgtk#13]
Hi,

If I run the script, and issue a "show" command in bluetoothctl, I can see the PAN uuid. 

From the android phone, I have trouble keeping a connection, but when the devices are paired I see the option to use for internet access, but it fails. Any ideas how I can make this work?

I want to run a PAN server on my Ubuntu box. I want to connect to the Ubuntu box via bluetooth from iPhone and Android, and then issue REST commands. Can I use this script to accomplish that?

**Comment by mk-fg** [comment]
Only used it with linux boxes, rather briefly, and few years ago by now, worked there, but no idea what android or iphone might need.
(guess you mean bt-pan script, there's like 100 of different scripts in this landfill of a repository)

I think by "internet access" such user-friendly devices typically mean "link + dhcp + gateway + access-to-specific-host-on-the-internet" - that script only helps with a "link" part, and you didn't mention everything else, so I'd guess that problem might be there - i.e. these devices won't treat it as "internet access" until they can successfully do all these steps and get ack from some Apple/Google host on the internet.

But that's just a guess - again, don't really know how anything works on these devices, never used any kind of tethering on one - so you probably don't want to ask me about that :)
