### ISSUE TITLE
base64 encoding discrepancy

### ISSUE THREAD

**Issue by jchevali** [mk-fg/fgtk#14]
Something is not right…  I get different base64-encoded result depending on whether I use the default option or I use hex option then transform to base64 (notice the different symbols around 'D', i.e., `+D+` vs `-D-`).

Why is that?  Is it because the base64 transform you're using is "urlsafe"?  Could we not have a switch to use ordinary base64 instead?

Thanks.

`
ssh-keyparse.py -s AedTQX1orIJQ4lyDtM4LiY0vTiELzSiL1EmFNrdy684=
AedTQX1orIJQ4lyDtM4LiY0vTiELzSiL1EmFNrdy685cD9bgfGqnSchnrugs-D-Ths6A0rVCAg7wAUX8R0Mnpw==
`

`
ssh-keyparse.py -s AedTQX1orIJQ4lyDtM4LiY0vTiELzSiL1EmFNrdy684= -x | xxd -r -p | base64 -w 0
AedTQX1orIJQ4lyDtM4LiY0vTiELzSiL1EmFNrdy685cD9bgfGqnSchnrugs+D+Ths6A0rVCAg7wAUX8R0Mnpw==
`

**Comment by mk-fg** [comment]
Yeah, it's that urlsafe thing.

For base64 encoding, rfc3548 defines this alphabet - https://tools.ietf.org/html/rfc3548.html#section-3 - with + and /, and then also "URL and Filename Safe Alphabet" in the next section - https://tools.ietf.org/html/rfc3548.html#section-4
I just use latter everywhere as there seem to be no good reason to ever use former, as it seem to be only different in that it doesn't work for some use-cases.
Decoders can parse both alphabets - both "+"/"-" and "/"/"_" as the same bits, but I know they rarely do that.

Added --base64-alt option for the section-3 alphabet too, though guess you can also get it via `| tr ...` using `ssh-keyparse -r | base64` or such.
