### ISSUE TITLE
vfat_shuffler: Randomization crashes: get_chain() missing 1 required positional argument: 'clidx'

### ISSUE THREAD

**Issue by cweiske** [mk-fg/fgtk#22]
Randomizing a directory crashes here:
```
$ sudo ./bin/vfat_shuffler --umount /dev/sdb1 / -s
Traceback (most recent call last):
  File "./bin/vfat_shuffler", line 667, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./bin/vfat_shuffler", line 659, in main
    op_reorder(path, src, dry_run=opts.dry_run, **sort_opts)
  File "./bin/vfat_shuffler", line 489, in op_reorder
    slice_map = path.get_slice_map()
  File "./bin/vfat_shuffler", line 205, in get_slice_map
    return list(map(self.fs.get_slice, self.get_chain()))
TypeError: get_chain() missing 1 required positional argument: 'clidx'
```

Full debug log: [vfat_shuffler_posarg.log](https://github.com/mk-fg/fgtk/files/5204022/vfat_shuffler_posarg.log)

**Comment by mk-fg** [comment]
Huh, guess I never ran it on a root at all, given this and the other bug with ".".
c649c7e should fix the issue, I think.

**Comment by cweiske** [comment]
Unfortunately not :)

```
$ sudo ./bin/vfat_shuffler --umount /dev/sdb1 / -s
Traceback (most recent call last):
  File "./bin/vfat_shuffler", line 667, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./bin/vfat_shuffler", line 659, in main
    op_reorder(path, src, dry_run=opts.dry_run, **sort_opts)
  File "./bin/vfat_shuffler", line 489, in op_reorder
    slice_map = path.get_slice_map()
  File "./bin/vfat_shuffler", line 205, in get_slice_map
    return list(map(self.fs.get_slice, self.get_chain()))
  File "./bin/vfat_shuffler", line 295, in get_chain
    while clidx < 0xffffff8: # last cluster is 0xffffff8-0xfffffff
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Log: [vfat_shuffler_posarg2.log](https://github.com/mk-fg/fgtk/files/5204091/vfat_shuffler_posarg2.log)

**Comment by cweiske** [comment]
Ah. just saw you made another commit. I'll try.

**Comment by cweiske** [comment]
No, still same error even with commit 17c2f03.

**Comment by mk-fg** [comment]
Yeah, I've messed it up like 5 times, sorry.
1b78802 should be the fix, didn't really test it either, but you get the idea - just pass it first cluster of the thing and it'll work.

**Comment by cweiske** [comment]
It finally worked! Many thanks for writing this tool, and fixing it so quickly.

**Comment by mk-fg** [comment]
No problem.
Still have a dumb mp3 player that requires it myself, and mostly need to use it every other week with -o option, after rss-get or toogg scripts from here.
